#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Velkar WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar-keygen ./build/docs/velkar-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Velkar WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar-rpc ./build/docs/velkar-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Velkar WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar-core ./build/docs/velkar-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Velkar WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar ./build/docs/velkar.ts
else
    echo "building keygen"
    typedoc --name "Velkar WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar-keygen ./build/docs/velkar-keygen.ts
    echo "building rpc"
    typedoc --name "Velkar WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar-rpc ./build/docs/velkar-rpc.ts
    echo "building core"
    typedoc --name "Velkar WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar-core ./build/docs/velkar-core.ts
    echo "building full"
    typedoc --name "Velkar WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/velkar ./build/docs/velkar.ts

fi